name: SymfonyUidDoctrine - Configuration
on: [ push, pull_request ]
jobs:
  project:
    name: Configuration
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # https://github.com/azohra/shell-linter (community)
      - name: Lint check
        uses: azohra/shell-linter@v0.3.0
        with:
          path: "docker/php/scripts"
